export interface InformationForm {
  id?: number; // Optional, as it may be auto-generated by the backend
  leader: string; // Represents the leader's name
  title: string; // Title of the form
  value: number; // Numeric value (decimal in backend)
  valueControl: boolean; // Boolean to control value validation
  priority: number; // Priority level (e.g., 1-5)
  status: string; // Status string (e.g., "Active", "Pending", etc.)
}
